INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-1', N'2LT', N'second leutinent')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-10', N'GEN', N'general')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-2', N'1LT', N'first leutinent')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-3', N'CPT', N'captain')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-4', N'MAJ', N'major')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-5', N'LTC', N'leutinent colonel')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-6', N'COL', N'colonel')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-7', N'BG', N'brigader general')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-8', N'MG', N'major general')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'O-9', N'LTG', N'leutinent general')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'SPECIAL', N'GA', N'general of the army')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'W-1', N'WO1', N'warrant officer')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'W-2', N'CW2', N'cheif warrant officer 2')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'W-3', N'CW3', N'cheif warrant officer 3')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'W-4', N'CW4', N'cheif warrant officer 4')
INSERT INTO [dbo].[OfficerRanks] ([O_grade], [abbr], [title]) VALUES (N'W-5', N'CW5', N'cheif warrant officer 5')