INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-1', N'2LT', N'second leutinent')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-10', N'GEN', N'general')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-2', N'1LT', N'first leutinent')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-3', N'CPT', N'captain')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-4', N'MAJ', N'major')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-5', N'LTC', N'leutinent colonel')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-6', N'COL', N'colonel')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-7', N'BG', N'brigader general')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-8', N'MG', N'major general')
INSERT INTO [dbo].[EnlistedRanks] ([E_grade], [abbr], [title]) VALUES (N'E-9', N'LTG', N'leutinent general')