INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20010', N'pistol', 331, N'ashok leyland DS')
INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20011', N'rifle', 332, N'bharat dynamics limited')
INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20012', N'sniper', 333, N'bharat dhatu nigam')
INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20013', N'shotgun', 334, N'ordinance factories')
INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20014', N'machine gun', 335, N'mazagon dock limited')
INSERT INTO [dbo].[Inventory] ([Batch_id], [Weapon_type1], [Supplier_id], [Supplier_Plant]) VALUES (N'20017', N'revolver', 336, N'delhi dynamics')